smeijer/unimported

src/__tests__/fs.ts, src/__tests__/help.ts, src/index.ts, src/process.ts
I just wanted to use this on a project under Windows today, and discovered that it wasn't finding any matches (so all files were being returned as not imported).
I did some debugging in my `node_modules` folder and discovered that the comparison (`.has(x)`) ends up comparing a path that looks like: `C:\\Repositories\\file.tsx` with `C:/Repositories/files.tsx`, so I changed the lines to `.has(x.replace(/\\/g, '/'))` and started seeing results like I was expecting.
I'm not sure what you'd prefer - running the replace inline during the `.has()`, or if we want to do it in index.ts on line 135 (where you resolve the glob `'**/*'`). As such, feel free to give me some feedback as to how you'd like it done.
I haven't validated if there are any other Windows issues yet.
=> feat: add support for windows

README.md, src/__tests__/cli.ts, src/__tests__/help.ts, src/config.ts, src/meta.ts
- Added ability to add `aliases` to config
- Updated documentation
- Updated tests
Using aliases outside of Tsconfig requires (possibly) a additional `rootDir` to be set in the config to allow matching from the base path.
To pass the 90% threshold for code coverage, I have also added a couple of minor additional tests - checking for invalid config json & importing in next.js
This may also fix #20.
closes #26
=> feat: support loading path aliases from config file

jest.config.js, package.json, src/__tests__/cli.ts, src/__tests__/help.ts, src/index.ts
This allows new files that are not yet tracked in git to be excluded from reporting.
=> feat: add option to ignore untracked files

package.json, src/__tests__/cli.ts
Need to have recent enough libs to support this. New installs would likely be covered by ^, but making explicit to allow for existing installs to be updated.
=> feat: add support for override keyword in typescript

package.json, src/__tests__/cli.ts, src/cache.ts, src/index.ts, src/traverse.ts
This utilizes the same caching mechanism as eslint to reduce eval time. Dropped 5 seconds off of pre-push hook for our mid-sized codebase.
=> feat: use cache for eval

package.json, src/__tests__/help.ts, src/index.ts, src/traverse.ts
I uncovered a few issues when I tried to run the tests locally.
1. TypeScript now treats errors in a catch block as `unknown` which means properties like "message" and "path" cannot be accessed. I've included a workaround to this which doesn't alter the implementation, but a better solution would be to handle instances of specific error classes with a fallback for unanticipated errors.
2. The "en" locale doesn't appear to be valid in any operating system I could find. For me it needed to be "en_US.utf8". From what I could tell searching around it looked like macos uses the same locale and Windows uses "un-US". I've included those changes although it might be useful to actually run the tests on those platforms to make sure it'll work.
3. There was a regression in the …
=> fix: local builds with updated dependencies.

src/process.ts
Currently, files from the superdir are cropped in the print output. This PR updates the logic and ensures that we, instead, simply remove `context.cwd + '/'`.
=> Fix path printing

package-lock.json, package.json, src/ensureArray.ts, src/fs.ts, src/traverse.ts
Updates following dependencies to latest version:
- `"@typescript-eslint/parser": "^5.27.1"`
- `"@typescript-eslint/typescript-estree": "^5.27.1"`
Closes #85.
=> Update deps @typescript-eslint/parser, @typescript-eslint/typescript-estree to ^5.27.1

src/__tests__/cli.ts, src/traverse.ts
In Vue 3 you can use both typescript and the setup script.
```
<script setup lang="ts">
import './script-setup-ts-imported';
</script>
```
However the current Vue script tag Regex looks for only ONE of the following "setup|lang|src". To be able to handle the syntax above for Vue 3 setup scripts a minor change to the regex is required. 
This PR makes the regex modification and adds a test to ensure that the syntax above will work.
=> feat: add support for vue3 setup typescript

README.md
Following [this comment](https://github.com/smeijer/unimported/issues/62#issuecomment-947985418), this adds a new "Troubleshooting" section about the need to include `.d.ts` in the list of extension when [TypeScript Declaration Files](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) are explicitly imported in TypeScript projects.
Happy to update the wording if there's any suggestions :slightly_smiling_face: 
I was also wondering why `.d.ts` wouldn't be included in the list of default extensions, but started with this as it was already suggested in the linked comment.
=> Add Troubleshooting section on TypeScript Declaration Files

src/__tests__/cli.ts, src/traverse.ts
In vue 3 it's possible to have two script import in one file see:
https://vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script
To be able to parse this kind of file the extractFromScriptTag function must be changed.
This PR try to solve this problem 
@smeijer
=> feat: add support for vue3 setup Usage alongside normal script

README.md, src/__tests__/cli.ts, src/config.ts, src/index.ts, src/traverse.ts
This is useful for TypeScript projects outputing pure ESM.
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm.
Closes #66.
=> feat: add regex path transformation

src/__tests__/cli.ts, src/traverse.ts
Hiya :wave:
The project previously added support for ```import(`template-literal`)```, but not for ```require(`template-literal`)``` (https://github.com/smeijer/unimported/pull/29).
This PR extracts the existing logic for `import()` to a function, and uses it to add support within `require()` statements. It also handles "weird" cases like `require()` (empty) or `require(...something)` (spreads)...because it makes TypeScript less complainy 💅
I added some tests for `await`'d `import`s too, just for completeness, as they were referenced in the `traverse.ts` comments.
=> feat: support template literals in require()s

src/__tests__/cli.ts, src/__tests__/help.ts, src/__tests__/print.ts, src/index.ts, src/print.ts
This PR is created for the issue: https://github.com/smeijer/unimported/issues/106
It adds the following flags:
--show-unused-files
--show-unused-deps
--show-unresolved-imports
To print their outputs separately.
If no flag is passed then all output is shown by default
=> feat: added format flags for unused, unimported and unresolved to print them separately

.all-contributorsrc
Thanks for the mention in the readme!
A quick PR to fix my profile URL - upleveled.io is my business, not me
=> chore: Fix profile URL

src/config.ts
Closes https://github.com/smeijer/unimported/issues/108
Allow to config ignore in entry config. Then it will be passed to the glob options.
```
{
"entry": [
{
"file": "pages/**/*.tsx",
"ignore": ["**/_*", "**/_*/**"]
}
]
}
```
=> feat: allow to config ignore entries

src/cache.ts
Makes sure that windows can also resolve the package.json file, which is needed to included the version number as cache key.
=> fix: ensure package.json can be resolved on windows

package-lock.json, package.json, src/__tests__/cli.ts, src/config.ts
Fixes #118 
Introduces `cosmiconfig` as requested in #118 in order to support loading the config from alternative file formats like:
```
.unimportedrc.js
.unimportedrc.yml
package.json > "unimported" key
```
I'm using `cosmiconfigSync` utilities instead of the async version, despite them being available since the `getConfig` is an async method.  When we use the async equivalent, we hit a segfault in Node as a result of `cosmiconfig` trying to call a dynamic import on the file within a Jest context that doesn't allow it to. Patched in a recent version of Node, and once  the test infra can require the latest version it should be fine to switch to the async version. 
See https://github.com/nodejs/node/issues/35889 and https://github.com/jestjs/jest/issues/11438
I haven't made any efforts to …
=> Add support for alternative config files with cosmiconfig

src/presets/react-native.ts
This pull request introduces support for Expo in the React Native preset. Expo projects typically utilize the `main` key in `package.json` as their entry point, linking to `AppEntry.js`.
The addition of Expo support ensures that unimported will seamlessly integrate with Expo out of the box. This enhancement is crucial for Expo React Native projects, providing a smoother development experience.
Please review the changes and provide any feedback or suggestions. Your input is greatly appreciated.
Thank you!
=> feat: Add Expo Support for React Native Preset

src/__tests__/cli.ts, src/process.ts
Fixes #190 by using the `unresolved` entry's `toString` (rather than its first part) to check for its presence inside the `ignoreUnresolved` index.
=> fix: `ignoreUnresolved`

src/process.ts
Pull #184 incorrectly mapped relative paths to absolute ones. This change undo's that.
=> fix: ensure relative paths are used
